### ISSUE TITLE
Too many arguments to block call, expected 1, have 3

### ISSUE THREAD

**Issue by LeBlaaanc** [oney/react-native-webrtc#381]
I'm probably just using the wrong RN version but it seems this module should support latest RN?

#### Expected behavior
Should compile?

#### Observed behavior
Compiler errors with:
```
MyProject/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m:122:25: Too many arguments to block call, expected 1, have 3
```

#### Steps to reproduce the problem
Maybe his happens with RN 0.50.1 using pods installation method?

#### Platform information

* **React Native version**:
0.50.1

* **Plugin version**:
master and 1.58.3

* ** POD Configuration**:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ShowcaseLive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyProject
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

end
```

**Comment by zxcpoiu** [comment]
Have not tried newer version of RN yet. I'm sure it support at least RN 0.47.

if there are any breaking changes in newer RN version you are using, feel free to fire a PR. thanks!

**Comment by LeBlaaanc** [comment]
I found that installing manually helped this error, not sure what’s different between those two methods to cause this error.

**Comment by zxcpoiu** [comment]
Hmm...I am not using `pod` to install.
anyway, glad you solved it

**Comment by saghul** [comment]
Working fine with RN 0.50.1 here. Are you using the bundled WebRTC framework or a different one?
